from sklarpy.multivariate._distributions._params._normal import MultivariateNormalParams
from sklarpy.multivariate._distributions._params._student_t import MultivariateStudentTParams
from sklarpy.multivariate._distributions._params._generalized_hyperbolic import MultivariateGenHyperbolicParams
